Pin xargo to v0.3.25
As xargo v0.3.26 contains breaking changes, specifically this: https://github.com/japaric/xargo/compare/v0.3.25...v0.3.26#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L147-R148 which caused an `error[E0463]: can't find crate for "core"` error when building

Co-authored-by: Reuven Podmazo <reuven@enigma.co>